/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS 0x40021000UL
#define RCC_CFGR_REG_OFFSET 0x04UL
#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDRESS + RCC_CFGR_REG_OFFSET)
#define RCC_AHB_CLOCK_ENABLE_REGISTER_OFFSET 0x14UL
#define RCC_AHB_CLOCK_ENABLE_REGISTER_ADDRESS (RCC_BASE_ADDRESS + RCC_AHB_CLOCK_ENABLE_REGISTER_OFFSET)
#define GPIOA_BASE_ADDR 0x48000000UL
#define GPIOA_MODE_REG_OFFSET 0x00UL
#define GPIOA_ALTERNATE_FUNCTION_REGISTER_OFFSET 0x20UL
#define GPIOA_ALTERNATE_FUNCTION_REGISTER_ADDRESS (GPIOA_BASE_ADDR + GPIOA_ALTERNATE_FUNCTION_REGISTER_OFFSET)

int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
	*pRccCfgrReg |= (0x5 << 24);

	//AHB2 Bus clock enable

	uint32_t *pRccAhbClockEnableReg = (uint32_t*) RCC_AHB_CLOCK_ENABLE_REGISTER_ADDRESS;
	*pRccAhbClockEnableReg |= (1 << 17); // enable for GPIOA


	// Configure GPIOA // PA_0

	uint32_t *pGPIOModeReg = (uint32_t*) (GPIOA_BASE_ADDR + GPIOA_MODE_REG_OFFSET);
	*pGPIOModeReg |=  0xA8000000UL;
	*pGPIOModeReg |= (0x2 << 0);

	// CONFIGURE alternation function register to set the mode

	uint32_t *pGPIOAAltFunLowReg = (uint32_t*) GPIOA_ALTERNATE_FUNCTION_REGISTER_ADDRESS;
	*pGPIOAAltFunLowReg |= (0xf); // not sure what is this

    /* Loop forever */
	for(;;);
}
