/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_CFGR_OFFSET 0x04U
#define RCC_ADDRESS 0x40021000U

#define ADC_CONFIGURATION_REGISTER_OFFSET  0x0CU
#define ADC_ADDRESS 0x50000000U

#define AHB_PERIPHERIAL_CLOCK_REGISTER_OFFSET  0x14U
#define AHB_PERIPHERIAL_CLOCK 0x40021000U

void setup_RCC_control_MCO () {
	uint32_t *RCC_ctrl = (uint32_t *)(RCC_ADDRESS + RCC_CFGR_OFFSET);
	*RCC_ctrl |= (1<<24);
	*RCC_ctrl |= (1<<26);
}

void setup_ADC_ALIGN(){
	uint32_t *ADC_conf = (uint32_t*)(ADC_ADDRESS + ADC_CONFIGURATION_REGISTER_OFFSET);
	*ADC_conf |= (1<<5);
}

void setup_AHB_PeripherialClock (){
	uint32_t *AHB_conf = (uint32_t*)(AHB_PERIPHERIAL_CLOCK + AHB_PERIPHERIAL_CLOCK_REGISTER_OFFSET);
	*AHB_conf |= (1<<28);
}

int main(void)
{
    /* Loop forever */
	setup_AHB_PeripherialClock(); // if You go without setting peripherial clock it wont set the bit for ADC peripherial.
	setup_ADC_ALIGN();
	setup_RCC_control_MCO();
	for(;;);
}
