/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SRAM_ADDRESS 0x20000004U

int main(void)
{
	uint32_t value = 0;
	uint32_t volatile *p = (uint32_t*)SRAM_ADDRESS; // without volatile with optimalization it wont work and we will be stuck on while(1) loop
	while(1){
		value = *p;
		if(value) break;
	}

    /* Loop forever */
	for(;;);
	return 0;
}
