/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio_driver.h"
#include "string.h"

int delay(void){
    for (volatile uint32_t i = 0; i < 500000; i++);
}

void config_gpio_onboard_led(GPIO_Handle_t *pGPIOHandle){
    pGPIOHandle->pGPIOx = GPIOA;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUTPUT;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOA,ENABLE);
    GPIO_Init(pGPIOHandle);
}

void config_gpio_onboard_button(GPIO_Handle_t *pGPIOHandle){
    pGPIOHandle->pGPIOx = GPIOB;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IT_RT;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
    pGPIOHandle->GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PD;
    GPIO_PeriClockControl(GPIOB,ENABLE);
    GPIO_Init(pGPIOHandle);
}

int main(void)
{
    GPIO_Handle_t gpioLed;
    GPIO_Handle_t gpioButton;
    memset(&gpioLed,0,sizeof(gpioLed));
    memset(&gpioButton,0,sizeof(gpioButton));
    config_gpio_onboard_led(&gpioLed);
    config_gpio_onboard_button(&gpioButton);
    GPIO_IRQConfig(IRQ_NO_EXTI10_15,5, ENABLE);

    /* Loop forever */
    while(1){
        // GPIO_WriteToOutputPin(gpioLed.pGPIOx,gpioLed.GPIO_PinConfig.GPIO_PinNumber, DISABLE);
    }
}

void EXTI15_10_IRQHandler(void){
    GPIO_IRQHandling(GPIO_PIN_NO_12);
    
    GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_5);
}
 
void EXTI1_IRQHandler(void){ 
    GPIO_IRQHandling(GPIO_PIN_NO_12);
}

void EXTI0_IRQHandler(void){
    GPIO_IRQHandling(GPIO_PIN_NO_12);
}
