/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio_driver.h"

int delay(void){
    for (volatile uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
    GPIO_Handle_t gpioLed;
    gpioLed.pGPIOx = GPIOA;
    gpioLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
    gpioLed.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUTPUT;
    gpioLed.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_HIGH;
    gpioLed.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
    gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_PeriClockControl(GPIOA,ENABLE);
    GPIO_Init(&gpioLed);
    
    /* Loop forever */
    while(1){
        GPIO_ToggleOutputPin(gpioLed.pGPIOx,gpioLed.GPIO_PinConfig.GPIO_PinNumber);
        delay();
    }

}
