/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define TIM2_IRQNO 28
#define I2C1_IRQNO 31

int main(void)
{
	//Generate the TIM2 global interrupt and I2C1 event interrupt peripheral using NVIC interrupt pending register and observer the execution of ISRs
	//when priorities are same and different.

    /* Loop forever */
	for(;;);
}
